### ISSUE TITLE
Request: Provide a Makefile or build instructions in Readme

### ISSUE THREAD

**Issue by androiddrew** [neuroprod/InsectRobotSimulation#1]
Found your video online and am really interested in your simulation tool. I don't have a lot of experience building CPP programs however. I am primarily a python programmer.

It would be nice to have a Makefile or some more detailed instructions on how to compile and run your tool.

**Comment by MagicRB** [comment]
yeah, would be nice. If you don't plan to do that, please remove the "should be cross-platform" part, since without added work by me, it's not true

**Comment by neuroprod** [comment]
Sorry guys, its open source, but not "download and ready to run, will be supported,  open source"
I just don't have the time for that. Sorry. 

To get started on your platform, check out the cinder link and see how you can run it on your platform. put my code in, and it will work.
if you'r on windows, there is a visual studio project that you can use. 

Feel free to make a makefile and send me a pull request, i will add it

**Comment by MagicRB** [comment]
I'd like to apologize for getting triggered, it's the quarantine and all, I'll throw this on my list of stuff I wanna do, I'll build you a CMake file

**Comment by oqu** [comment]
#2 should help for this.
