### ISSUE TITLE
Serial protocol/schema clarification

### ISSUE THREAD

**Issue by peterfelts** [neuroprod/InsectRobotSimulation#7]
Hi @neuroprod, I'm trying to build this project (thanks for posting the video and source). I'm currently at the point of trying to get the servos working and am having trouble understanding the serial data protocol. The simulation has a mSerialOut stream that appears to write the angle of each servo to the serial stream:

https://github.com/neuroprod/InsectRobotSimulation/blob/2f01750b40507ec957fba579fa3325852373004b/src/InsectRobotSimulationApp.cpp#L503C1-L524C4

But the remote appears to write the analog values for the joysticks and the values of various buttons:

https://github.com/neuroprod/InsectRobotSimulation/blob/2f01750b40507ec957fba579fa3325852373004b/Arduino/insectRemote/insectRemote.ino#L52C1-L56C4

Could you please help me understand the data format that the remote is sending and the microcontroller is expecting? What, conceptually, is the joystick sending?

I'm trying to hook up the output of the simulator (mSerialOut) to the serial input on the microcontroller, but I don't know if this will work or not.

Thank you.

**Comment by Fedefeo** [comment]
Hi Peter, I am also at this stage and would love any help from you.
I have already built the hexapod and done most of the wiring (although not sure if it's correct) and am stuck.
I have not had much luck contacting Kris, so if we are able to help each other that would be amazing....
let me know your thoughts. 
BTW, I am a product designer but not much of a Software guy. So baby talk, please :)

**Comment by peterfelts** [comment]
Hi @Fedefeo, I'd be happy to help. What are you currently stuck on?

**Comment by peterfelts** [comment]
@Fedefeo, I spent more time on this and I think that I have an understanding of what @neuroprod was doing here. The remote control reads the values of the joysticks and buttons and sends a series of 19 bytes out over the wire. Here is the protocol that I've been able to reverse from the (mostly) undocumented code:

![image](https://github.com/neuroprod/InsectRobotSimulation/assets/5828480/894342ed-e1e7-4124-a697-e5102891414d)

He's reading the A-to-D values from the joysticks as 16-bit integers which get split in to two bytes when serialized into this protocol. 

I've got my build pretty much working now. It's cool to see it move around on my workbench. :)

**Comment by neuroprod** [comment]
Sorry for the late reply, but yes, @peterfelts is correct, i send the 16 bit analog input in 2 bytes, (check the anloginput.h)
so the remote just sends raw data of its state.
The InsectRobotSimulationApp.cpp sends the  motor data (from the computer simulation) but for that to work you need the insectrobotUSB.ino flashed to the robot (this is what i used to test it first, all the IK was running on the computer at this point). 
If you use the remote,  you need the insectrobot.ino, it gets the joistick data, does his own IK and controles the motors

**Comment by peterfelts** [comment]
Hi @neuroprod I wanted to share this with you. I finally got by build working a few months back. 
For some reason the legs seem to collide with each other a bit while walking... I speculate that's due to the fact that I used a different microprocessor, one that has fewer ADC bits for conversion, and I might have gotten my math wrong in there somewhere. 

Anyway, thanks again for sharing this out. Fun project.

https://github.com/user-attachments/assets/e06a6deb-3481-44ba-bd98-d24d0123b53c

**Comment by neuroprod** [comment]
> Hi @neuroprod I wanted to share this with you. I finally got by build working a few months back. For some reason the legs seem to collide with each other a bit while walking... I speculate that's due to the fact that I used a different microprocessor, one that has fewer ADC bits for conversion, and I might have gotten my math wrong in there somewhere.
> 
> Anyway, thanks again for sharing this out. Fun project.
> 
>  hexapod_robot_small.mp4

Looks cool, great work! I think you can avoid the step overlap by making the max step distance smaller, or clamp the input
